### ISSUE TITLE
Update Terraform Infrastructure

### ISSUE THREAD

**Issue by harrisonmuskat** [6RiverSystems/github-default-branch#5]
### Changes to Infrastructure

- [ ] Create `main` branch in https://github.com/6RiverSystems/terraform-6rs-cluster-infrastructure
- [ ] Update all branch references from `master` to `main` in https://github.com/6RiverSystems/terraform-6rs-cfs-cluster and https://github.com/6RiverSystems/terraform-6rs-dev-cluster
- [ ] Test Terraform plan in both the above repos
- [ ] Delete `master` branch in https://github.com/6RiverSystems/terraform-6rs-cluster-infrastructure

### Changes to Dev and Prd Modules

- [ ] Create `main` branch in in https://github.com/6RiverSystems/terraform-6rs-cfs-cluster and https://github.com/6RiverSystems/terraform-6rs-dev-cluster
- [ ] Validate that Atlantis picks up changes in this branch
- [ ] Change default branch to `main`
- [ ] Delete `master` branch

**Comment by tonygaetani** [comment]
@AeroNotix can you :eyes: this and let us know if you have any :speech_balloon: please?

**Comment by AeroNotix** [comment]
All looks good to me.
